### ISSUE TITLE
Support for LWF-MC

### ISSUE THREAD

**Issue by prinshul** [fcdl94/MiBv2#1]
Hi

Is LWF-MC not supported?
Getting below as error:
run.py: error: argument --method: invalid choice: 'LWF-MC' (choose from 'FT', 'LWF', 'IC', 'ILT', 'EWC', 'RW', 'PI', 'MiB', 'PLOP')

Cmd:
python -m torch.distributed.launch --nproc_per_node=2 run.py --data_root data --batch_size 12 --dataset voc --name LWF-MC --task 15-5 --step 0 --lr 0.001 --epochs 30 --method LWF-MC

**Comment by fcdl94** [comment]
Please, use IC as the method name. There is an issue in the docs.
