### ISSUE TITLE
cannot find ADEChallengeData2016/training.txt

### ISSUE THREAD

**Issue by JFJ-Bin** [fcdl94/MiBv2#3]
Hi, I am facing a problem like below:
$ python -m torch.distributed.launch --nproc_per_node=2 run.py --data_root /home/ubuntu/MiBv2/data/ADEChallengeData2016/annotations/training --batch_size 12 --dataset ade --name L
WF --task 100-50 --step 0 --lr 0.01 --epochs 60 --method LWF
 
The problem is : FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/MiBv2/data/ADEChallengeData2016/annotations/training/ADEChallengeData2016/images/training'

Please help me to solve the problem..Thank you!

**Comment by fcdl94** [comment]
I think it is likely a path issue. Can you check the path of the file is correct? 
I think the data root should stop at `/home/ubuntu/MiBv2/data/`

**Comment by JFJ-Bin** [comment]
Thanks, but using the VOC dataset doesn't cause a bug, using ADE and following your change, it still reports an error：FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/MiBv2/data/ADEChallengeData2016/ADEChallengeData2016/training.txt'

**Comment by fcdl94** [comment]
You replicated twice the 'ADEChallengeData2016' in the path.
Use '/home/ubuntu/MiBv2/data/ADEChallengeData2016/training.txt' and it should work

**Comment by JFJ-Bin** [comment]
ok,thanks. So how do I train with my own dataset?
